[workspace]
name = "kale-monorepo"
version = "0.1.0"
members = [
    "editor",
    "apps/kv",
    "apps/lsp",
    "sys/sysmon",
    "packages/std",
    "packages/editor",
    "packages/bindings/win32",
    "libs/render",
    "libs/ui",
    "libs/framework",
    "libs/gl",
    "libs/net",
    "libs/term",
    "libs/json",
    "libs/matrix",
    "libs/sql"
]

[scripts]
test = "uv run pytest tests/"
check = "kale check editor/main.kl"
build-editor = "kale build editor/main.kl -o bin/kale_edit.exe"
build-kv = "kale build apps/kv/main.kl -o bin/kale_kv.exe"
registry = "kale registry start --port 8080"
git-lens = "kale run apps/git_lens/main.kl"
db-studio = "kale run apps/db_studio/main.kl"
api-client = "kale run apps/api_client/main.kl"
term = "kale run apps/term/main.kl"
shader-lab = "kale run apps/shader_lab/main.kl"
hex = "kale run apps/hex/main.kl"
perf = "kale run apps/perf/main.kl"
asset-studio = "kale run apps/asset_studio/main.kl"
tracker = "kale run apps/tracker/main.kl"
files = "kale run apps/files/main.kl"
audio-tracker = "kale run apps/audio_tracker/main.kl"
node-graph = "kale run apps/node_graph/main.kl"
markdown = "kale run apps/markdown/main.kl"
scene3d = "kale run apps/scene3d/main.kl"
packet = "kale run apps/packet/main.kl"
calc = "kale run apps/calc/main.kl"
font-forge = "kale run apps/font_forge/main.kl"
ui-designer = "kale run apps/ui_designer/main.kl"
mem-studio = "kale run apps/mem_studio/main.kl"
vector = "kale run apps/vector/main.kl"
