[package]
name = "kale-pkg-editor"
version = "0.1.0"
description = "Core editor components, syntax tokenizer, and buffer management"
authors = ["Tomlin7 <billydevbusiness@gmail.com>"]
license = "MIT"
edition = "2026"
entry = "editor.kl"

[dependencies]
std = { path = "../std" }
